# REST Client tests for /domains route.
@baseUrl = http://localhost:5000

# Get all domains
GET {{baseUrl}}/domains
###
GET {{baseUrl}}/domains/4
###
GET {{baseUrl}}/domains?id=4
###
GET {{baseUrl}}/domains?name=devoid.gr
###
GET {{baseUrl}}/domains?name=dev&per_page=3&page=1
