# REST Client tests for /pios route.
@baseUrl = http://localhost:5000

# Normal request.
GET {{baseUrl}}/pios?domain=devoid.gr
###
GET {{baseUrl}}/pios?domain=fps.gr
###
GET {{baseUrl}}/pios?domain=in.gr
###
GET {{baseUrl}}/pios?domain=fastpath.gr
###
GET {{baseUrl}}/pios?domain=odt.gr
###
GET {{baseUrl}}/pios?domain=cortex.gr
###
GET {{baseUrl}}/pios?domain=asdf.gr
###
GET {{baseUrl}}/pios?domain=cretaforce.gr


###

# "Fast" request.
GET {{baseUrl}}/pios?domain=devoid.gr&fast=true


###

# "Fresh" request.
GET {{baseUrl}}/pios?domain=devoid.gr&fresh=true
