# REST Client tests for /snapshots route.
@baseUrl = http://localhost:5000

# Get all snapshots
GET {{baseUrl}}/snapshots?per_page=1&page=0
###

# Get snapshots for a specific domain.
GET {{baseUrl}}/snapshots?domainId=1
###
GET {{baseUrl}}/snapshots?domainName=devoid.gr
###

# Get paginated snapshots.
GET {{baseUrl}}/snapshots?per_page=1&page=0
###
