// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kow_whois_api;

namespace kow_whois_api.Migrations
{
	[DbContext(typeof(WhoisContext))]
	[Migration("20191219183057_BigBang")]
	partial class BigBang
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "3.1.0")
				.HasAnnotation("Relational:MaxIdentifierLength", 64);

			modelBuilder.Entity("kow_whois_api.Domain", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnName("id")
						.HasColumnType("int");

					b.Property<DateTime>("CreatedAt")
						.ValueGeneratedOnAdd()
						.HasColumnName("created_at")
						.HasColumnType("datetime(6)");

					b.Property<DateTime?>("CreationDate")
						.HasColumnName("creation")
						.HasColumnType("datetime(6)");

					b.Property<DateTime?>("ExpirationDate")
						.HasColumnName("expiration")
						.HasColumnType("datetime(6)");

					b.Property<string>("Handle")
						.HasColumnName("handle")
						.HasColumnType("varchar(255) CHARACTER SET utf8mb4");

					b.Property<DateTime?>("LastUpdate")
						.HasColumnName("last_update")
						.HasColumnType("datetime(6)");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnName("name")
						.HasColumnType("varchar(255) CHARACTER SET utf8mb4");

					b.Property<string>("ProtocolNumber")
						.HasColumnName("protonum")
						.HasColumnType("varchar(128) CHARACTER SET utf8mb4")
						.HasMaxLength(128);

					b.Property<DateTime>("UpdatedAt")
						.ValueGeneratedOnAddOrUpdate()
						.HasColumnName("updated_at")
						.HasColumnType("datetime(6)");

					b.HasKey("Id");

					b.HasIndex("Handle")
						.IsUnique();

					b.HasIndex("Name")
						.IsUnique();

					b.ToTable("domain");
				});

			modelBuilder.Entity("kow_whois_api.NameServer", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnName("id")
						.HasColumnType("int");

					b.Property<DateTime>("CreatedAt")
						.ValueGeneratedOnAdd()
						.HasColumnName("created_at")
						.HasColumnType("datetime(6)");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnName("name")
						.HasColumnType("varchar(255) CHARACTER SET utf8mb4");

					b.Property<DateTime>("UpdatedAt")
						.ValueGeneratedOnAddOrUpdate()
						.HasColumnName("updated_at")
						.HasColumnType("datetime(6)");

					b.HasKey("Id");

					b.HasIndex("Name")
						.IsUnique();

					b.ToTable("nameserver");
				});

			modelBuilder.Entity("kow_whois_api.NameServerSnapshot", b =>
				{
					b.Property<int>("NameServerId")
						.HasColumnType("int");

					b.Property<int>("SnapshotId")
						.HasColumnType("int");

					b.HasKey("NameServerId", "SnapshotId");

					b.HasIndex("SnapshotId");

					b.ToTable("rel_nameserver_snapshot");
				});

			modelBuilder.Entity("kow_whois_api.Registrar", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnName("id")
						.HasColumnType("int");

					b.Property<DateTime>("CreatedAt")
						.ValueGeneratedOnAdd()
						.HasColumnName("created_at")
						.HasColumnType("datetime(6)");

					b.Property<string>("Name")
						.HasColumnName("name")
						.HasColumnType("varchar(255) CHARACTER SET utf8mb4");

					b.Property<DateTime>("UpdatedAt")
						.ValueGeneratedOnAddOrUpdate()
						.HasColumnName("updated_at")
						.HasColumnType("datetime(6)");

					b.Property<string>("email")
						.HasColumnName("email")
						.HasColumnType("longtext CHARACTER SET utf8mb4");

					b.Property<string>("phone")
						.HasColumnName("phone")
						.HasColumnType("varchar(20) CHARACTER SET utf8mb4")
						.HasMaxLength(20);

					b.Property<string>("url")
						.HasColumnName("url")
						.HasColumnType("longtext CHARACTER SET utf8mb4");

					b.HasKey("Id");

					b.HasIndex("Name")
						.IsUnique();

					b.ToTable("registrar");
				});

			modelBuilder.Entity("kow_whois_api.Snapshot", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnName("id")
						.HasColumnType("int");

					b.Property<DateTime>("CreatedAt")
						.ValueGeneratedOnAdd()
						.HasColumnName("created_at")
						.HasColumnType("datetime(6)");

					b.Property<int>("DomainId")
						.HasColumnName("domain_id")
						.HasColumnType("int");

					b.Property<int?>("RegistrarId")
						.HasColumnName("registrar_id")
						.HasColumnType("int");

					b.Property<DateTime>("UpdatedAt")
						.ValueGeneratedOnAddOrUpdate()
						.HasColumnName("updated_at")
						.HasColumnType("datetime(6)");

					b.HasKey("Id");

					b.HasIndex("DomainId");

					b.HasIndex("RegistrarId");

					b.ToTable("snapshot");
				});

			modelBuilder.Entity("kow_whois_api.NameServerSnapshot", b =>
				{
					b.HasOne("kow_whois_api.NameServer", "NameServer")
						.WithMany("NameServerSnapshots")
						.HasForeignKey("NameServerId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("kow_whois_api.Snapshot", "Snapshot")
						.WithMany("NameServerSnapshots")
						.HasForeignKey("SnapshotId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("kow_whois_api.Snapshot", b =>
				{
					b.HasOne("kow_whois_api.Domain", "Domain")
						.WithMany("Snapshots")
						.HasForeignKey("DomainId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("kow_whois_api.Registrar", "Registrar")
						.WithMany("Snapshots")
						.HasForeignKey("RegistrarId");
				});
#pragma warning restore 612, 618
		}
	}
}
