using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Net;

namespace KowWhoisApi.Models
{
	[Table("address")]
	public class Address
	{
		[Column("id")]
		public uint Id { get; set; }

		[Column("ip_raw")]
		[MaxLength(16)]
		[Required]
		public byte[] IpRaw { get; set; }

		[Column("ip")]
		public string Ip { get; set; }

		// Unmapped property, to make my life easier when handling results
		// from ns lookups. There is no reason to actually keep this object.
		[NotMapped]
		public IPAddress IPAddress
		{
			// get - just creates a new IPAddress from scratch, given the the
			//       IP bytes. Added to just not return a null object.
			get { return new IPAddress(IpRaw); }

			// set - keeps the only information saved in the database, the raw
			//       IP bytes. (IP string is being generated by the database.)
			set { IpRaw = value.GetAddressBytes(); }
		}

		[Column("created_at", TypeName = "TIMESTAMP")]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public DateTime CreatedAt { get; set; }

		[Column("updated_at", TypeName = "TIMESTAMP")]
		[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
		public DateTime UpdatedAt { get; set; }

		public virtual ICollection<NameServerAddress> NameServerAddresses { get; set; }

		public Address()
		{
			NameServerAddresses = new List<NameServerAddress>();
		}
	}
}
